### ISSUE TITLE
Version detected and error on viewing

### ISSUE THREAD

**Issue by icebird4all** [flybywiresim/fdr-analysis#4]
Hello Guys!

After my problem on plane crash after a turn over (Flight one from SVMG to SBBR - second from SBBR to SBGL) on takeoff, i tried to find any data for it with your fdr analyser. 
First problem, the Version detector tells me version 20 - my last is 19. It would convert the fdr to csv with the version 0 - but no luck on viewing the data - everytime get the error:

`Converting done.
Map: D:/FS2020/FDR/fdr2csv/2022-05-08-20-39-06.csv
fdr_analyser_ui.py:67: DtypeWarning: Columns (286,289) have mixed types.Specify dtype option on import or set low_memory=False.
  userinterface_windows(args)
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3361, in get_loc
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ap_sm.data.aircraft_position.lat'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "fdr_analyser_ui.py", line 1320, in <module>
    main(sys.argv[1:])
  File "fdr_analyser_ui.py", line 67, in main
    userinterface_windows(args)
  File "fdr_analyser_ui.py", line 289, in userinterface_windows
    draw_map_graph(pd.read_csv(values.get('csvfile')))
  File "fdr_analyser_ui.py", line 368, in draw_map_graph
    lat_samples = fdr['ap_sm.data.aircraft_position.lat'][1::50]
  File "pandas\core\frame.py", line 3458, in __getitem__
  File "pandas\core\indexes\base.py", line 3363, in get_loc
KeyError: 'ap_sm.data.aircraft_position.lat'
[19944] Failed to execute script 'fdr_analyser_ui' due to unhandled exception!

[Verarbeitung des Prozesses mit Code 1 (0x00000001) beendet]`

Any help welcome - thx!

icebird4all

**Comment by frankkopp** [comment]
We do not support this tool. It is meant to be used by fbw devs for development and support purposes only.
